"""Recompute the StandardScaler the training script fitted but never saved, decide whether the
model expects scaled or raw inputs (by accuracy on the held-out split), and write src/scaler.ts."""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras_model import build_model, CSV_PATH

data = pd.read_csv(CSV_PATH)
X = data.iloc[:, :-1].values.astype(np.float32)
y = data.iloc[:, -1].values.astype(np.float32)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler().fit(X_train)
model = build_model()


def acc(Xs):
    p = model.predict(Xs, verbose=0)[:, 0]
    return float(((p > 0.5) == (y_test > 0.5)).mean())


acc_raw = acc(X_test)
acc_scaled = acc(scaler.transform(X_test))
print(f"rows={len(X)} train={len(X_train)} test={len(X_test)} good_share={y.mean():.3f}")
print(f"held-out accuracy raw inputs   : {acc_raw:.4f}")
print(f"held-out accuracy scaled inputs: {acc_scaled:.4f}")
mean = [float(v) for v in scaler.mean_]
scale = [float(v) for v in scaler.scale_]
ts = f"""// GENERATED by scripts/export_scaler.py — do not edit by hand.
// StandardScaler refitted exactly as scripts/train_model.py did in the original repo
// (train_test_split(test_size=0.2, random_state=42) on outputs/pushup_keypoints_augmented.csv,
// {len(X)} rows). The scaler was never saved, so it is recomputed and baked here.
// Held-out accuracy of pushup_model_augmented.h5: raw inputs {acc_raw:.4f}, scaled inputs {acc_scaled:.4f}.
export const MEAN: readonly number[] = {json.dumps(mean)};
export const SCALE: readonly number[] = {json.dumps(scale)};

/** (x - mean) / scale, feature-wise, like sklearn's StandardScaler.transform. */
export function scale(vector: readonly number[]): number[] {{
  if (vector.length !== MEAN.length) throw new Error(`expected ${{MEAN.length}} features, got ${{vector.length}}`);
  return vector.map((v, i) => (v - MEAN[i]) / SCALE[i]);
}}
"""
open("src/scaler.ts", "w").write(ts)
json.dump({"mean": mean, "scale": scale, "acc_raw": acc_raw, "acc_scaled": acc_scaled}, open("scripts/scaler.json", "w"))
print("wrote src/scaler.ts")
